language: python
python:
    - "3.7"
cache: pip
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq --no-install-recommends asciidoctor pandoc plantuml ruby-sass
install:
    - pip install -U -r requirements.txt
    # Installing pelican in editable mode makes its tests.support package available to us
    - pip install -e git+https://github.com/getpelican/pelican.git#egg=pelican
    # The following commands install all plugins dependencies.
    # The `rm`, `grep` & `sed commands` below are needed because some submodules have conflicting requirements.
    # cf. https://github.com/getpelican/pelican-plugins/issues/1170
    - rm pelicanthemes-generator/requirements.txt
    - pip install -U -r <(grep -hv pelican */requirements.txt | sed 's/==/>=/')
# We need to exclude the multimarkdown_reader plugin,
# otherwise its MmdReader class will be loaded by pelican.readers.Readers,
# and override the default .md one:
script: nosetests --exclude-dir=multimarkdown_reader --with-summary-report
